import Head from 'next/head'
import Image from 'next/image'
import { useState } from 'react';
import styles from '../styles/Home.module.css'

export default function Home({ data }) {
  
  const [allStories, setAllStories] = useState(data);
  console.log(allStories);
  const [story, setStory] = useState('https://via.placeholder.com/600/d32776')
  const [showStory, setShowStory] = useState(false)

  function openStory(e) {
    setShowStory(true)
    setStory(e.target.dataset.id)
  }

  function prev() {
    let current = allStories.find(item => item.url === story)
    let prev = allStories.find(item => item.id + 1 === current.id)
    setStory(prev.url)
  }

  function next() {
    let current = allStories.find(item => item.url === story)
    let next = allStories.find(item => item.id - 1 === current.id)
    setStory(next.url)
  }

  return (
    <div className={styles.container}>
      <Head>
        <title>NextJS Stories by Adarsh M</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
        <div className={`${styles.story} ${showStory ? styles.showStory: styles.hide}`}>
              <Image src={`${story}`} height="190" width="190" alt="as" />
              <button onClick={prev}>Prev</button>
              <button onClick={next}>Next</button>
              <button onClick={() => setShowStory(false) }>Close</button>
        </div>
      <div className={styles.nextStoriesContainer}>
        {data.map((item, index) => {
          return (
              <div onClick={(e) => openStory(e)} data-id={item.url} key={index} className={styles.nextStory} style={{background: `url(${item.thumbnailUrl})`, backgroundPosition: 'center'}}>
              </div>
          )
        })}

      </div>
     
    </div>
  )
}

export async function getStaticProps() {
  const res = await fetch('https://jsonplaceholder.typicode.com/photos/?_limit=10')
  const data = await res.json();
  // console.log(data);
  return {
    props: {
      data
    }
  }
}
